name = "azumaya-calendar"
compatibility_date = "2024-02-12"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
NODE_VERSION = "20.0.0"

[[d1_databases]]
binding = "DB"
database_name = "azumaya-calendar-db"
database_id = "fceeddc3-00b7-4fa9-9f79-fe8194c2ebc6"
migrations_dir = "drizzle"
preview_database_id = "DB"


